-- ============================================================================
-- Pie360 — Friends & Portfolio Sharing  ·  Supabase SQL Schema
-- ============================================================================
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query).
-- Safe to run multiple times: all statements use IF NOT EXISTS / OR REPLACE.
--
-- Tables
--   friendships          — connection requests + accepted friendships
--   invite_tokens        — one-time shareable links (7-day expiry)
--   portfolio_snapshots  — user-published portfolio snapshots for comparison
--
-- Identity key: user_email  (may be an E.164 phone string for phone-only users)
-- ============================================================================


-- ── 0. Enable pgcrypto for gen_random_uuid() ─────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================================
-- TABLE 1: friendships
-- ============================================================================
-- Stores all connection states between pairs of users.
-- A single row represents the canonical edge between two users.
-- Direction matters: requester_email initiated the connection.
--
-- status values:
--   pending   — request sent, not yet accepted or rejected
--   accepted  — both parties connected
--   rejected  — recipient declined (kept so requester can re-send later)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.friendships (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    requester_email  text        NOT NULL,
    recipient_email  text        NOT NULL,
    status           text        NOT NULL DEFAULT 'pending'
                                 CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),

    -- Only one row per ordered pair — prevents duplicate requests
    CONSTRAINT friendships_pair_unique UNIQUE (requester_email, recipient_email),

    -- Users can't add themselves
    CONSTRAINT friendships_no_self_loop CHECK (requester_email <> recipient_email)
);

-- Indexes for the two query patterns used by friends_store.py
CREATE INDEX IF NOT EXISTS idx_friendships_requester
    ON public.friendships (requester_email, status);

CREATE INDEX IF NOT EXISTS idx_friendships_recipient
    ON public.friendships (recipient_email, status);

-- Auto-update updated_at on every row change
CREATE OR REPLACE FUNCTION public._set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_friendships_updated_at ON public.friendships;
CREATE TRIGGER trg_friendships_updated_at
    BEFORE UPDATE ON public.friendships
    FOR EACH ROW EXECUTE FUNCTION public._set_updated_at();


-- ============================================================================
-- TABLE 2: invite_tokens
-- ============================================================================
-- One-time invite links generated by a user and sent to anyone (even
-- non-Pie360 users). When the recipient signs in and visits the link:
--   1. consume_invite_token() marks the row with used_by
--   2. An accepted friendship is inserted / updated
--
-- Token is a UUID4 — stored as text so URL handling stays simple.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.invite_tokens (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    token       text        NOT NULL UNIQUE,
    created_by  text        NOT NULL,   -- email of the person who generated it
    used_by     text,                   -- email of the person who consumed it (NULL = unused)
    created_at  timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz NOT NULL    -- set to created_at + 7 days by the app
);

-- Fast lookup by token (primary URL-param access pattern)
CREATE INDEX IF NOT EXISTS idx_invite_tokens_token
    ON public.invite_tokens (token);

-- Let creators see tokens they generated (e.g. future "my active invites" UI)
CREATE INDEX IF NOT EXISTS idx_invite_tokens_created_by
    ON public.invite_tokens (created_by);


-- ============================================================================
-- TABLE 3: portfolio_snapshots
-- ============================================================================
-- One row per user. Upserted (on_conflict=user_email) on every publish.
-- friends_store.get_friend_snapshot() applies the share_* flags server-side
-- (the SELECT still returns all columns — privacy enforcement is in Python).
--
-- holdings_json shape:
--   [{"ticker": "AAPL", "weight": 12.5}, ...]   (weight in %)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.portfolio_snapshots (
    id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_email          text        NOT NULL UNIQUE,
    display_name        text,                           -- optional display alias
    holdings_json       jsonb       NOT NULL DEFAULT '[]'::jsonb,
    share_holdings      boolean     NOT NULL DEFAULT false,
    share_performance   boolean     NOT NULL DEFAULT false,
    share_risk_metrics  boolean     NOT NULL DEFAULT false,
    cycle_phase         text,                           -- e.g. "Mid / Expansion"
    recession_prob      numeric(5,2),                  -- 0.00 – 100.00
    published_at        timestamptz,                    -- NULL = never published
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- Index for the primary query pattern (lookup by user_email)
CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_email
    ON public.portfolio_snapshots (user_email);

-- Auto-update updated_at
DROP TRIGGER IF EXISTS trg_snapshots_updated_at ON public.portfolio_snapshots;
CREATE TRIGGER trg_snapshots_updated_at
    BEFORE UPDATE ON public.portfolio_snapshots
    FOR EACH ROW EXECUTE FUNCTION public._set_updated_at();


-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
-- Enable RLS on all three tables.
-- Policies are written for the Supabase anon + service_role key setup used
-- by the Streamlit backend (which calls Supabase via the service_role key
-- through get_client() — bypasses RLS).
--
-- If you switch to user-JWT auth (Supabase Auth), replace the policies below
-- with auth.uid()-based variants — see NOTES at bottom.
-- ============================================================================

-- friendships ─────────────────────────────────────────────────────────────────
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;

-- Service role (Streamlit backend) has full access
DROP POLICY IF EXISTS "service_role_all_friendships" ON public.friendships;
CREATE POLICY "service_role_all_friendships"
    ON public.friendships FOR ALL
    USING (true)
    WITH CHECK (true);

-- invite_tokens ───────────────────────────────────────────────────────────────
ALTER TABLE public.invite_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all_invite_tokens" ON public.invite_tokens;
CREATE POLICY "service_role_all_invite_tokens"
    ON public.invite_tokens FOR ALL
    USING (true)
    WITH CHECK (true);

-- portfolio_snapshots ─────────────────────────────────────────────────────────
ALTER TABLE public.portfolio_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all_snapshots" ON public.portfolio_snapshots;
CREATE POLICY "service_role_all_snapshots"
    ON public.portfolio_snapshots FOR ALL
    USING (true)
    WITH CHECK (true);


-- ============================================================================
-- OPTIONAL: Cleanup job for expired tokens
-- ============================================================================
-- Run this periodically (pg_cron or Supabase scheduled function) to purge
-- expired / used tokens and keep the table lean.
--
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- SELECT cron.schedule(
--     'purge-expired-invite-tokens',
--     '0 3 * * *',   -- 3am UTC daily
--     $$DELETE FROM public.invite_tokens
--       WHERE (expires_at < now()) OR (used_by IS NOT NULL AND created_at < now() - interval '30 days')$$
-- );


-- ============================================================================
-- VERIFICATION QUERIES — run to confirm tables exist and RLS is on
-- ============================================================================
SELECT
    table_name,
    pg_size_pretty(pg_total_relation_size(quote_ident(table_name)::regclass)) AS size
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('friendships', 'invite_tokens', 'portfolio_snapshots')
ORDER BY table_name;

SELECT
    tablename,
    rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN ('friendships', 'invite_tokens', 'portfolio_snapshots');


-- ============================================================================
-- NOTES: Migrating to Supabase Auth JWT policies (future)
-- ============================================================================
-- When Pie360 switches to passing user JWTs from the frontend, replace the
-- catch-all service_role policies above with user-scoped variants, e.g.:
--
-- CREATE POLICY "users_read_own_friendships"
--     ON public.friendships FOR SELECT
--     USING (
--         auth.jwt() ->> 'email' = requester_email
--         OR auth.jwt() ->> 'email' = recipient_email
--     );
--
-- CREATE POLICY "users_insert_own_request"
--     ON public.friendships FOR INSERT
--     WITH CHECK (auth.jwt() ->> 'email' = requester_email);
--
-- CREATE POLICY "users_update_own_friendships"
--     ON public.friendships FOR UPDATE
--     USING (auth.jwt() ->> 'email' IN (requester_email, recipient_email));
