[theme]
base                     = "light"
primaryColor             = "#3b7ddd"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f5f7fb"
textColor                = "#293241"
font                     = "sans serif"
